version: '3'
services:
  db: 
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=php_docker
      - MYSQL_USER=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_TCP_PORT=3306
    volumes:
      - "./api/db:/docker-entrypoint-initdb.d"

  www:
    image: php:apache
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_DBHOST=db
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=root
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
